#define I  //prefix highlights illegal instructions
#define op(id, name, ...) case id: return op_##name(__VA_ARGS__);
#define fp(name) &MOS6502::fp_##name

auto MOS6502::instruction() -> void {
  switch(readPC()) {
  op(0x00, brk)
  op(0x01, read_indirect_zero_page_x, fp(ora))
I op(0x02, stp)
I op(0x03, rmwr_indirect_zero_page_x, fp(asl), fp(ora))
I op(0x04, nop_zero_page)
  op(0x05, read_zero_page, fp(ora))
  op(0x06, rmw_zero_page, fp(asl))
I op(0x07, rmwr_zero_page, fp(asl), fp(ora))
  op(0x08, php)
  op(0x09, read_immediate, fp(ora))
  op(0x0a, shift, fp(sla))
I op(0x0b, anc_immediate)
I op(0x0c, nop_absolute)
  op(0x0d, read_absolute, fp(ora))
  op(0x0e, rmw_absolute, fp(asl))
I op(0x0f, rmwr_absolute, fp(asl), fp(ora))
  op(0x10, branch, r.p.n, 0)
  op(0x11, read_indirect_zero_page_y, fp(ora))
I op(0x12, stp)
I op(0x13, rmwr_indirect_zero_page_y, fp(asl), fp(ora))
I op(0x14, nop_zero_page_x)
  op(0x15, read_zero_page_x, fp(ora))
  op(0x16, rmw_zero_page_x, fp(asl))
I op(0x17, rmwr_zero_page_x, fp(asl), fp(ora))
  op(0x18, clear_flag, r.p.c.bit)
  op(0x19, read_absolute_y, fp(ora))
I op(0x1a, nop)
I op(0x1b, rmwr_absolute_y, fp(asl), fp(ora))
I op(0x1c, nop_absolute_x)
  op(0x1d, read_absolute_x, fp(ora))
  op(0x1e, rmw_absolute_x, fp(asl))
I op(0x1f, rmwr_absolute_x, fp(asl), fp(ora))
  op(0x20, jsr_absolute)
  op(0x21, read_indirect_zero_page_x, fp(and))
I op(0x22, stp)
I op(0x23, rmwr_indirect_zero_page_x, fp(rol), fp(and))
  op(0x24, read_zero_page, fp(bit))
  op(0x25, read_zero_page, fp(and))
  op(0x26, rmw_zero_page, fp(rol))
I op(0x27, rmwr_zero_page, fp(rol), fp(and))
  op(0x28, plp)
  op(0x29, read_immediate, fp(and))
  op(0x2a, shift, fp(rla))
I op(0x2b, anc_immediate)
  op(0x2c, read_absolute, fp(bit))
  op(0x2d, read_absolute, fp(and))
  op(0x2e, rmw_absolute, fp(rol))
I op(0x2f, rmwr_absolute, fp(rol), fp(and))
  op(0x30, branch, r.p.n, 1)
  op(0x31, read_indirect_zero_page_y, fp(and))
I op(0x32, stp)
I op(0x33, rmwr_indirect_zero_page_y, fp(rol), fp(and))
I op(0x34, nop_zero_page_x)
  op(0x35, read_zero_page_x, fp(and))
  op(0x36, rmw_zero_page_x, fp(rol))
I op(0x37, rmwr_zero_page_x, fp(rol), fp(and))
  op(0x38, set_flag, r.p.c.bit)
  op(0x39, read_absolute_y, fp(and))
I op(0x3a, nop)
I op(0x3b, rmwr_absolute_y, fp(rol), fp(and))
I op(0x3c, nop_absolute_x)
  op(0x3d, read_absolute_x, fp(and))
  op(0x3e, rmw_absolute_x, fp(rol))
I op(0x3f, rmwr_absolute_x, fp(rol), fp(and))
  op(0x40, rti)
  op(0x41, read_indirect_zero_page_x, fp(eor))
I op(0x42, stp)
I op(0x43, rmwr_indirect_zero_page_x, fp(lsr), fp(eor))
I op(0x44, nop_zero_page)
  op(0x45, read_zero_page, fp(eor))
  op(0x46, rmw_zero_page, fp(lsr))
I op(0x47, rmwr_zero_page, fp(lsr), fp(eor))
  op(0x48, push, r.a)
  op(0x49, read_immediate, fp(eor))
  op(0x4a, shift, fp(sra))
I op(0x4b, alr_immediate)
  op(0x4c, jmp_absolute)
  op(0x4d, read_absolute, fp(eor))
  op(0x4e, rmw_absolute, fp(lsr))
I op(0x4f, rmwr_absolute, fp(lsr), fp(eor))
  op(0x50, branch, r.p.v, 0)
  op(0x51, read_indirect_zero_page_y, fp(eor))
I op(0x52, stp)
I op(0x53, rmwr_indirect_zero_page_y, fp(lsr), fp(eor))
I op(0x54, nop_zero_page_x)
  op(0x55, read_zero_page_x, fp(eor))
  op(0x56, rmw_zero_page_x, fp(lsr))
I op(0x57, rmwr_zero_page_x, fp(lsr), fp(eor))
  op(0x58, clear_flag, r.p.i.bit)
  op(0x59, read_absolute_y, fp(eor))
I op(0x5a, nop)
I op(0x5b, rmwr_absolute_y, fp(lsr), fp(eor))
I op(0x5c, nop_absolute_x)
  op(0x5d, read_absolute_x, fp(eor))
  op(0x5e, rmw_absolute_x, fp(lsr))
I op(0x5f, rmwr_absolute_x, fp(lsr), fp(eor))
  op(0x60, rts)
  op(0x61, read_indirect_zero_page_x, fp(adc))
I op(0x62, stp)
I op(0x63, rmwr_indirect_zero_page_x, fp(ror), fp(adc))
I op(0x64, nop_zero_page)
  op(0x65, read_zero_page, fp(adc))
  op(0x66, rmw_zero_page, fp(ror))
I op(0x67, rmwr_zero_page, fp(ror), fp(adc))
  op(0x68, pull, r.a)
  op(0x69, read_immediate, fp(adc))
  op(0x6a, shift, fp(rra))
I op(0x6b, arr_immediate)
  op(0x6c, jmp_indirect_absolute)
  op(0x6d, read_absolute, fp(adc))
  op(0x6e, rmw_absolute, fp(ror))
I op(0x6f, rmwr_absolute, fp(ror), fp(adc))
  op(0x70, branch, r.p.v, 1)
  op(0x71, read_indirect_zero_page_y, fp(adc))
I op(0x72, stp)
I op(0x73, rmwr_indirect_zero_page_y, fp(ror), fp(adc))
I op(0x74, nop_zero_page_x)
  op(0x75, read_zero_page_x, fp(adc))
  op(0x76, rmw_zero_page_x, fp(ror))
I op(0x77, rmwr_zero_page_x, fp(ror), fp(adc))
  op(0x78, set_flag, r.p.i.bit)
  op(0x79, read_absolute_y, fp(adc))
I op(0x7a, nop)
I op(0x7b, rmwr_absolute_y, fp(ror), fp(adc))
I op(0x7c, nop_absolute_x)
  op(0x7d, read_absolute_x, fp(adc))
  op(0x7e, rmw_absolute_x, fp(ror))
I op(0x7f, rmwr_absolute_x, fp(ror), fp(adc))
I op(0x80, nop_immediate) // r.y
  op(0x81, store_indirect_zero_page_x, r.a)
I op(0x82, nop_immediate) // r.x
I op(0x83, store_indirect_zero_page_x, r.a & r.x)
  op(0x84, store_zero_page, r.y)
  op(0x85, store_zero_page, r.a)
  op(0x86, store_zero_page, r.x)
I op(0x87, store_zero_page, r.a & r.x)
  op(0x88, decrement, r.y)
I op(0x89, nop_immediate) // r.a
  op(0x8a, transfer, r.x, r.a, 1)
I op(0x8b, xaa_immediate)
  op(0x8c, store_absolute, r.y)
  op(0x8d, store_absolute, r.a)
  op(0x8e, store_absolute, r.x)
I op(0x8f, store_absolute, r.a & r.x)
  op(0x90, branch, r.p.c, 0)
  op(0x91, store_indirect_zero_page_y, r.a)
I op(0x92, stp)
I op(0x93, sha_indirect_zero_page_y)
  op(0x94, store_zero_page_x, r.y)
  op(0x95, store_zero_page_x, r.a)
  op(0x96, store_zero_page_y, r.x)
I op(0x97, store_zero_page_y, r.a & r.x)
  op(0x98, transfer, r.y, r.a, 1)
  op(0x99, store_absolute_y, r.a)
  op(0x9a, transfer, r.x, r.s, 0)
I op(0x9b, tas_absolute_y)
I op(0x9c, shy_absolute_x)
  op(0x9d, store_absolute_x, r.a)
I op(0x9e, shx_absolute_y)
I op(0x9f, sha_absolute_y)
  op(0xa0, read_immediate, fp(ldy))
  op(0xa1, read_indirect_zero_page_x, fp(lda))
  op(0xa2, read_immediate, fp(ldx))
I op(0xa3, read_indirect_zero_page_x, fp(lax))
  op(0xa4, read_zero_page, fp(ldy))
  op(0xa5, read_zero_page, fp(lda))
  op(0xa6, read_zero_page, fp(ldx))
I op(0xa7, read_zero_page, fp(lax))
  op(0xa8, transfer, r.a, r.y, 1)
  op(0xa9, read_immediate, fp(lda))
  op(0xaa, transfer, r.a, r.x, 1)
I op(0xab, lxa_immediate)
  op(0xac, read_absolute, fp(ldy))
  op(0xad, read_absolute, fp(lda))
  op(0xae, read_absolute, fp(ldx))
I op(0xaf, read_absolute, fp(lax))
  op(0xb0, branch, r.p.c, 1)
  op(0xb1, read_indirect_zero_page_y, fp(lda))
I op(0xb2, stp)
I op(0xb3, read_indirect_zero_page_y, fp(lax))
  op(0xb4, read_zero_page_x, fp(ldy))
  op(0xb5, read_zero_page_x, fp(lda))
  op(0xb6, read_zero_page_y, fp(ldx))
I op(0xb7, read_zero_page_y, fp(lax))
  op(0xb8, clear_flag, r.p.v.bit)
  op(0xb9, read_absolute_y, fp(lda))
  op(0xba, transfer, r.s, r.x, 1)
I op(0xbb, las_absolute_y)
  op(0xbc, read_absolute_x, fp(ldy))
  op(0xbd, read_absolute_x, fp(lda))
  op(0xbe, read_absolute_y, fp(ldx))
I op(0xbf, read_absolute_y, fp(lax))
  op(0xc0, read_immediate, fp(cpy))
  op(0xc1, read_indirect_zero_page_x, fp(cmp))
I op(0xc2, nop_immediate)
I op(0xc3, dcp_indirect_zero_page_x)
  op(0xc4, read_zero_page, fp(cpy))
  op(0xc5, read_zero_page, fp(cmp))
  op(0xc6, rmw_zero_page, fp(dec))
I op(0xc7, rmw_zero_page, fp(dcp))
  op(0xc8, increment, r.y)
  op(0xc9, read_immediate, fp(cmp))
  op(0xca, decrement, r.x)
I op(0xcb, axs_immediate)
  op(0xcc, read_absolute, fp(cpy))
  op(0xcd, read_absolute, fp(cmp))
  op(0xce, rmw_absolute, fp(dec))
I op(0xcf, rmw_absolute, fp(dcp))
  op(0xd0, branch, r.p.z, 0)
  op(0xd1, read_indirect_zero_page_y, fp(cmp))
I op(0xd2, stp)
I op(0xd3, dcp_indirect_zero_page_y)
I op(0xd4, nop_zero_page_x)
  op(0xd5, read_zero_page_x, fp(cmp))
  op(0xd6, rmw_zero_page_x, fp(dec))
I op(0xd7, rmw_zero_page_x, fp(dcp))
  op(0xd8, clear_flag, r.p.d.bit)
  op(0xd9, read_absolute_y, fp(cmp))
I op(0xda, nop)
I op(0xdb, dcp_absolute_y)
I op(0xdc, nop_absolute_x)
  op(0xdd, read_absolute_x, fp(cmp))
  op(0xde, rmw_absolute_x, fp(dec))
I op(0xdf, rmw_absolute_x, fp(dcp))
  op(0xe0, read_immediate, fp(cpx))
  op(0xe1, read_indirect_zero_page_x, fp(sbc))
I op(0xe2, nop_immediate)
I op(0xe3, rmwr_indirect_zero_page_x, fp(inc), fp(sbc))
  op(0xe4, read_zero_page, fp(cpx))
  op(0xe5, read_zero_page, fp(sbc))
  op(0xe6, rmw_zero_page, fp(inc))
I op(0xe7, rmwr_zero_page, fp(inc), fp(sbc))
  op(0xe8, increment, r.x)
  op(0xe9, read_immediate, fp(sbc))
  op(0xea, nop)
I op(0xeb, read_immediate, fp(sbc))
  op(0xec, read_absolute, fp(cpx))
  op(0xed, read_absolute, fp(sbc))
  op(0xee, rmw_absolute, fp(inc))
I op(0xef, rmwr_absolute, fp(inc), fp(sbc))
  op(0xf0, branch, r.p.z, 1)
  op(0xf1, read_indirect_zero_page_y, fp(sbc))
I op(0xf2, stp)
I op(0xf3, rmwr_indirect_zero_page_y, fp(inc), fp(sbc))
I op(0xf4, nop_zero_page_x)
  op(0xf5, read_zero_page_x, fp(sbc))
  op(0xf6, rmw_zero_page_x, fp(inc))
I op(0xf7, rmwr_zero_page_x, fp(inc), fp(sbc))
  op(0xf8, set_flag, r.p.d.bit)
  op(0xf9, read_absolute_y, fp(sbc))
I op(0xfa, nop)
I op(0xfb, rmwr_absolute_y, fp(inc), fp(sbc))
I op(0xfc, nop_absolute_x)
  op(0xfd, read_absolute_x, fp(sbc))
  op(0xfe, rmw_absolute_x, fp(inc))
I op(0xff, rmwr_absolute_x, fp(inc), fp(sbc))
  }
}

#undef I
#undef op
#undef fp
