install:
	if [ -d /usr/share/nSide/Video\ Shaders ]; then sudo rm -r /usr/share/nSide/Video\ Shaders; fi
	sudo mkdir -p /usr/share/nSide/Video\ Shaders
	sudo cp -r *.shader /usr/share/nSide/Video\ Shaders
	sudo chmod -R 777 /usr/share/nSide/Video\ Shaders
